FROM python:3.11-slim

WORKDIR /app

# Зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY task6/rag_bot_yandexGPT_defended.py .

# Запускаем бота
CMD ["python", "rag_bot_yandexGPT_defended.py"]